-- InterviewCoach PostgreSQL schema
--
-- Do not apply this file on production.
-- Source of truth:
--   backend/schema.sql          — full schema for new environments
--   database/migrations/*.sql   — incremental changes (apply in filename order)
--
-- See database/README.md
